### ISSUE TITLE
react-native run-ios error

### ISSUE THREAD

**Issue by xuanskyer** [Bob1993/mdcc-client#5]
```
React packager ready.

2017-01-17 18:57 node[79168] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-01-17 18:57 node[79168] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1007:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1400:11)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
~
```

```

** BUILD SUCCEEDED **


Installing build/Build/Products/Debug-iphonesimulator/MdccClient.app
No devices are booted.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/MdccClient.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by manajay** [comment]
2017-06-02 10:01:14.370 [fatal][tid:main] Unable to resolve module react/lib/ReactUpdates from /Users/pdid-7/Downloads/mdcc-client-master/node_modules/react-native/Libraries/react-native/react-native.js: Module does not exist in the module map or in these directories:
  /Users/pdid-7/Downloads/mdcc-client-master/node_modules/react-native/node_modules/react/lib
,  /Users/pdid-7/Downloads/mdcc-client-master/node_modules/react/lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

**Comment by liuyanhongwl** [comment]
I had same problem, and I solve it use next step:

1. upgrade 'react-native'  [React Native升级指南|v0.40+升级适配经验与心得](http://www.devio.org/2017/01/17/React-Native%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97-v0.40+%E5%8D%87%E7%BA%A7%E9%80%82%E9%85%8D%E7%BB%8F%E9%AA%8C%E4%B8%8E%E5%BF%83%E5%BE%97/)
2. then 'react-native run-ios' will error because Navigator is deprecated in react-native v0.43. We can use 'react-native-deprecated-custom-components' in next step:
2.1. `npm install react-native-deprecated-custom-components --save`
2.2. `import {Navigator} from 'react-native-deprecated-custom-components'`

**Comment by poberwong** [comment]
@liuyanhongwl Thanks a lot
